---
name: Checks for PRs
on:
  pull_request:
  push:
    branches-ignore:
      - master
jobs:
  tests:
    name: Tests on ${{ matrix.arch }}
    runs-on:
      - ubuntu-latest
      - ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Tests
        run: make check
