name: Testing clients
on:
  - push
  - pull_request
jobs:
  build:
    name: Build beanstalkd
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    steps:
      - uses: actions/checkout@v4
      - run: make
      - uses: actions/upload-artifact@v4
        with:
          name: beanstalkd-${{ matrix.arch }}
          path: beanstalkd-${{ matrix.arch }}
  pheanstalk:
    name: Test Pheanstalk PHP
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    continue-on-error: true
    needs:
      - build
    steps:
      - name: Verify architecture
        run: uname -m
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpunit
      - uses: actions/download-artifact@v4
        with:
          name: beanstalkd-${{ matrix.arch }}
      - name: Start beanstalkd for ${{ matrix.arch }}
        run: chmod +x ./beanstalkd-${{ matrix.arch }} && ./beanstalkd-${{ matrix.arch }} &
      - uses: actions/checkout@v4
        with:
          repository: pheanstalk/pheanstalk
          ref: v5
      - name: Install dependencies including dev-dependencies
        run: composer install
      - name: Run tests
        run: phpunit
        env:
          SERVER_HOST: localhost
  greenstalk:
    name: Test Greenstalk Python
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: [ 3.9 ]
        arch: [ amd64, arm64 ]
    needs:
      - build
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v4
        with:
          repository: justinmayhew/greenstalk
      - uses: actions/download-artifact@v4
        id: download
        with:
          #include-hidden-files: true
          name: beanstalkd-${{ matrix.arch }}
      - name: Make beanstalkd executable for ${{ matrix.arch }}
        run: chmod +x ${{steps.download.outputs.download-path}}/beanstalkd-${{ matrix.arch }}
      - name: Run beanstalkd -v
        run: ${{steps.download.outputs.download-path}}/beanstalkd-${{ matrix.arch }} -v

      - name: Install dependencies
        run: |
          pip install pytest
          pip install .
      - name: Run tests
        env:
          BEANSTALKD_PATH: ${{steps.download.outputs.download-path}}/beanstalkd-${{ matrix.arch }}
        run: make test
  pystalk:
    name: Test Pystalk Python
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: [ "3.10" ]
        arch: [ amd64, arm64 ]
    needs:
      - build
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v4
        with:
          repository: EasyPost/pystalk
      - uses: actions/download-artifact@v4
        id: download
        with:
          name: beanstalkd-${{ matrix.arch }}
      - name: Make beanstalkd executable for ${{ matrix.arch }}
        run: chmod +x ${{steps.download.outputs.download-path}}/beanstalkd-${{ matrix.arch }}
      - name: Run beanstalkd -v
        run: ${{steps.download.outputs.download-path}}/beanstalkd-${{ matrix.arch }} -v
      - name: Install dependencies
        run: python -m pip install -r requirements-tests.txt -e .
      - name: Run tests
        env:
          BEANSTALKD_PATH: ${{steps.download.outputs.download-path}}/beanstalkd-${{ matrix.arch }}
        run: pytest tests/
